### ISSUE TITLE
LFS experience link is broken

### ISSUE THREAD

**Issue by asfarley** [NlightNFotis/nlightnfotis.github.io#7]
I saw you posted a link on Reddit to your post, but the direct link isn't working although the article appears to still exist.

**Comment by NlightNFotis** [comment]
Hello.

Thanks for bringing this issue to my notice. Unfortunatelly, I couldn't do more things to remedy
the situation, since it appears to be archived (or I couldn't post a comment to it?), so I just edited a comment I had made there to contain a link to the post.

Thanks again, and sorry for the delayed response.
